version: 2.1 



orbs:

    node: circleci/node@5.0.2

  

  

commands:

  start-minikube:

    steps:



        - node/install:

            install-yarn: true

            node-version: '18'

        - node/install-packages:

            pkg-manager: yarn

            include-branch-in-cache-key: false

            cache-version: v4

        - run:

            name: Run tests

            command: docker run rockymoyosu/pymod:latest

        - run:

            name: Build

            command: yarn nx affected:build





  test:

    steps:

      - run: 

          name: Running all unit tests 

          command: |

            echo "Success" 

 

jobs: 

  test: 

    parameters: 

        machine: 

          type: string 

          default: ubuntu-2004:202104-01 

    machine: 

      image: << parameters.machine >> 

 

    steps: 

      - start-minikube

      - test

      

workflows: 

  version: 2 

  test-all-versions: 

    jobs: 

      - test: 

          machine: ubuntu-2004:202104-01 

      - test: 

          machine: ubuntu-2004:202104-01 

      - test: 

          machine: ubuntu-2004:202104-01 

      - test: 

          machine: ubuntu-2004:202104-01 

      - test: 

          machine: ubuntu-2004:202104-01
